/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIndexRouteImport } from './routes/ticket/index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/ticket': typeof TicketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/ticket': typeof TicketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/ticket/': typeof TicketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ticket/$ticketId' | '/ticket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ticket/$ticketId' | '/ticket'
  id: '__root__' | '/' | '/ticket/$ticketId' | '/ticket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  TicketIndexRoute: typeof TicketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  TicketIndexRoute: TicketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
